config/routes.rb
Impulsideas::Application.routes.draw do
  post 'ipn_notifications/:contribution_id',
    to: 'payment_notifications#create',
    as: 'ipn_notifications'

  get 'contact_form/new'
  get 'contact_form/create'
  get 'about/faq'
  get 'about/faq_en'
  get 'about/index'
  get 'about/main'
  get 'about/terms'
  get 'about/terms_en'
  get 'about/landing'
  get 'about', to: 'about#index', as: 'about'

  resources :contact_form, only: :create
  resources :payment_notifications

  mount RedactorRails::Engine => '/redactor_rails'

  resources :projects do
    resources :items, shallow: true
    get 'orders', on: :member
  end

  resources :orders, except: [:update, :destroy, :new, :edit] do
    get 'execute', on: :member
    get 'event/:event' => 'orders#event', on: :member, as: 'event'
  end

  get 'items', to: 'items#index', as: 'items'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }

  root 'about#main'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  extended_description :text
#  funding_goal         :float
#  funding_duration     :integer
#  category             :string(255)
#  tags                 :string(255)
#  user_id              :integer
#  created_at           :datetime
#  updated_at           :datetime
#  media_link           :string(255)
#  media_meta           :text
#  project_url          :string(255)
#  short_description    :text
#
# TODO: 3 min. products.
# TODO: total_contributed (order payed and beyond) and total_completed ().
#
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :items, dependent: :destroy
  has_many :orders, through: :items

  validates :title, presence: true
  validates :short_description, presence: true, length: { minimum: 5 }
  validates :extended_description, presence: true, length: { minimum: 50 }
  validates :funding_goal, presence: true, numericality: { greater_than: 0.0 }
  validates :funding_duration, presence: true, numericality: {
    greater_than: 0, less_than_or_equal_to: 90
  }
  validates :media_link, presence: true,
    format: URI::regexp(%w(http https))
  validates :project_url, :allow_blank => true,
    format: URI::regexp(%w(http https))

  after_save :get_video_info

  def to_param
    "#{id} #{title}".parameterize
  end

  def total_contributed
    Project.where(id: self.id)
      .where("orders.workflow_state='completed'")
      .joins(items: :orders)
      .sum(:amount)
      .to_f
  end

  def total_contributors
    Project.where(id: self.id)
      .where("orders.workflow_state='completed'")
      .joins(items: :orders)
      .select('DISTINCT orders.user_id').count
  end

  def time_left
    return 0 unless created_at
    left = funding_duration - ((Time.now - created_at)/1.day).round
    left > 0 ? left : 0
  end

  def funding_percentage
    return 0.0 unless funding_goal.to_f > 0
    ((total_contributed.to_f / funding_goal.to_f) * 100)
  end

  def get_video_info
    if self.media_link.present?
      video = VideoInfo.get self.media_link
      self.update_columns(media_meta: video.to_yaml)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :orders]
  before_action :authenticate_user!, except: [:index, :show, :orders]
  before_action :check_can_edit, only: [:edit, :update, :destroy]
  before_action :set_creator, only: [:show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/1/orders
  # GET /projects/1/orders.json
  def orders
    @orders = Order.completed.by(@project)
    render 'orders/index'
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :short_description,
                                      :extended_description, :funding_goal,
                                      :funding_duration, :category, :tags,
                                      :media_link, :project_url)
    end

    def set_creator
      @creator = @project.user == current_user || current_user.try(:admin?)
    end

    # verify if is user creator
    def check_can_edit
      return true if current_user.admin?
      unless @project.user == current_user
        err_msg = 'No puedes modificar este proyecto.'
        flash[:error] = err_msg
        respond_to do |format|
          format.html { redirect_to @project }
          format.json { render json: err_msg, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<section class="margined">
  <h1>Proyecto</h1>
  <hr class="star-primary">

  <div class="row">
    <div class="col-md-8">
      <%= simple_form_for(@project) do |f| %>
        <%= f.error_notification %>

          <div class="form-inputs">
            <div class="form-group well">
              <%= f.input :title, label: 'Título', input_html: { class: 'form-control' }, placeholder: 'Título del proyecto' %>
            </div>

            <div class="form-group well">
              <%= f.input :media_link, label: 'Link video (youtube o vimeo)', input_html: { class: 'form-control' }, placeholder:
              'http://www.youtube.com/watch?v=EDUpiVwi6lw' %>
            </div>

            <div class="form-group well">
              <%= f.input :short_description, label: 'Breve Descripción', input_html: { class: 'form-control' }, placeholder: 'Atraiga contribuidores a su proyectos en una pocas lineas.' %>
            </div>

            <div class="form-group well">
              <%= f.input :extended_description, label: 'Descripción Detallada', input_html: {
              class: 'form-control redactor', rows: 100 }, placeholder:
              'Descripción del proyecto: overview, plan de negocios, etapas...' %>
            </div>

            <div class="form-group well">
              <%= f.input :funding_goal, label: 'Meta', input_html: { class: 'form-control' },
              placeholder: 'Cantidad de fondos deseada.' %>
            </div>

            <div class="form-group well">
              <%= f.input :funding_duration, label: 'Duración', input_html: { class:
              'form-control' }, placeholder: 'Elija duración de 1 a 90 días.' %>
            </div>

            <div class="form-group well">
              <%= f.input :project_url, label: 'URL del Proyecto', input_html: { class: 'form-control' }, placeholder:
              'http://www.su-proyecto.com' %>
            </div>

            <%#=f .input :category %>
            <%#=f .input :tags %>
          </div>

          <button type="submit" id="submit" class="btn btn-primary">Salvar</button>
          <%=link_to 'Atrás', projects_path, class: 'btn btn-danger' %>
            <% end %>
    </div>

    <div class="col-md-4">
      <h2>Vista Previa</h2>
      <div id="preview">
        <%= render 'project_thumbnail', project: Project.new %>
      </div>
    </div>
  </div>
</section>

app/views/projects/_project_thumbnail.html.erb
<% user = (project.user || current_user).emailname rescue 'anonimo' %>
<div id="project_thumbnail">
  <div class="thumbnail" id="<%= project.id %>">
      <% if project.new_record?  %>
        <%= image_tag 'http://placehold.it/300x200', alt: 'placeholder', class: 'img-responsive' %>
      <% else %>
        <%
          media_meta = YAML.load(project.media_meta) rescue nil
          if media_meta.respond_to?(:thumbnail_large)
        %>
          <%= link_to project, role: 'button' do %>
            <%= image_tag media_meta.thumbnail_large, class: 'img-responsive'  %>
          <% end %>
        <% end %>
      <% end %>
    <div class="caption">
      <h3><span id="title"><%= project.title %></span> <small>por <%= user %></small></h3>
      <p id="description"><%= truncate(project.short_description, length: 100) %></p>

      <hr>

      <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= project.funding_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.funding_percentage %>%">
          <span class="sr-only"><%= project.funding_percentage %>% Complete (success)</span>
        </div>
        <p>
          <% if project.new_record? %>
            <span><%= number_to_currency(project.total_contributed) %></span>
          <% end %>
          <span class="pull-right"><%= project.funding_percentage.round %>%</span>
        </p>
      </div>

      <p>
        <% if project.new_record? %>
          Meta <strong id="goal"><%= number_to_currency(project.funding_goal) %></strong>
          en
          <i class="fa fa-clock-o"></i> <strong id="duration"><%= project.funding_duration %></strong> días.
        <% else %>
          <strong id="goal"><%= number_to_currency(project.total_contributed) %></strong> recolectados
          <i class="fa fa-clock-o"></i> <strong id="duration"><%= project.time_left %></strong> días restantes.
        <% end %>
      </p>

      <% unless project.new_record? %>
        <p>
          <%= link_to 'Contribuir', project, class: 'btn btn-primary', role: 'button' %>
          <%= link_to 'Ver mas', project, class: 'btn btn-success', role: 'button' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<!-- <h1>Editing project</h1> -->

<%= render 'form' %>

<!-- <%#= link_to 'Show', @project %> | -->
<%#= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h3 class="title">Proyectos</h3>
<% if @projects.any? %>
  <div id="projects_container">
    <% @projects.each do |project| %>
      <div class="col-sm-6 col-md-4 project_item">
        <%= render 'project_thumbnail', project: project %>
      </div>
    <% end %>
  </div>
<% else %>
  <br><br>
  <p>No proyectos para mostrar. Crea uno nuevo <%= link_to "aqui.", new_project_path %> </p>
<% end %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="row project_show">
  <div class="col-md-8">
    <div class="jumbotron">
      <h1><%= @project.title %> <small>por <%= @project.user.emailname %></small></h1>
      <p class="lead"><%= @project.short_description %></p>
      <%
        media_meta = YAML.load(@project.media_meta) rescue nil
        if media_meta.respond_to?(:embed_code)
      %>
        <div class="video-container">
          <%=raw media_meta.embed_code %>
        </div>
      <% end %>

      <br>

      <% unless @project.project_url.blank? %>
        <dt>Pagina del Proyecto:</dt>
        <dd><%= link_to @project.project_url, @project.project_url, id: 'project_url', target: '_blank' %></dd>
      <% end %>
    </div>

    <p>
      <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      <iframe src="//www.facebook.com/plugins/like.php?href=<%= URI.encode(request.original_url) %>&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21&amp;appId=420436051410681" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
    </p>

    <p><%=raw @project.extended_description %></p>

    <% if @creator %>
      <hr>
      <%= link_to 'Editar', edit_project_path(@project), class: 'btn btn-primary' %>
      <%= link_to 'Eliminar', project_path(@project), class: 'btn btn-danger', method: :delete, data: { confirm: 'Está seguro que quiere eliminar este proyecto?' }  %>
    <% end %>
    <%= link_to 'Ver todos', projects_path, class: 'btn btn-default' %>
  </div>

  <div class="col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= number_to_currency(@project.total_contributed || 0) %> <small>USD</small></h3>
        <p>de un total de <%= number_to_currency(@project.funding_goal) %></p>

        <h3><%= @project.time_left %> <small>DIAS</small></h3>
        <p>de un total de <%= @project.funding_duration %> dias</p>

        <h3><%= @project.total_contributors %> <small>CONTRIBUYENTE(S)</small></h3>
        <p>ver <%= link_to 'lista', orders_project_path(@project) %> de aportes</p>

        <!-- <br> -->
        <!-- <p><%#= link_to 'Contribuye!', new_project_contribution_path(@project), class: 'btn btn-success', role: 'button' %></p> -->
      </div>
    </div>
    <div class="thumbnail">
      <% if @project.items.any? %>
        <div class="caption">
          <h3>Productos soportando este projecto:</h3>
        </div>
        <% @project.items.each do |item| %>
          <%= render 'items/item_thumbnail', item: item %>
        <% end %>
      <% end %>
      <br>
      <i class="fa fa-plus-square"></i> <%= link_to 'Crear nuevo producto', new_project_item_path(@project) %>
    </div>
  </div>
</div>