config/routes.rb
Impulsideas::Application.routes.draw do
  post 'ipn_notifications/:contribution_id',
    to: 'payment_notifications#create',
    as: 'ipn_notifications'

  get 'contact_form/new'
  get 'contact_form/create'
  get 'about/faq'
  get 'about/faq_en'
  get 'about/index'
  get 'about/main'
  get 'about/terms'
  get 'about/terms_en'
  get 'about/landing'
  get 'about', to: 'about#index', as: 'about'

  resources :contact_form, only: :create
  resources :payment_notifications

  mount RedactorRails::Engine => '/redactor_rails'

  resources :projects do
    resources :items, shallow: true
    get 'orders', on: :member
  end

  resources :orders, except: [:update, :destroy, :new, :edit] do
    get 'execute', on: :member
    get 'event/:event' => 'orders#event', on: :member, as: 'event'
  end

  get 'items', to: 'items#index', as: 'items'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }

  root 'about#main'
end

app/models/contribution.rb
# == Schema Information
#
# Table name: contributions
#
#  id             :integer          not null, primary key
#  amount         :float
#  project_id     :integer
#  user_id        :integer
#  payment_status :string(255)      default("UNPROCESSED")
#  anonymous      :boolean          default(FALSE)
#  created_at     :datetime
#  updated_at     :datetime
#

class Contribution < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  belongs_to :project
  belongs_to :user
  has_many :payment_notifications, dependent: :destroy

  validates :amount, numericality: { greater_than: 0 }, presence: true
  validates :user_id, presence: true
  validates :project_id, presence: true

  def paypal_url
    @preapproval = PAYPAL_API.build_preapproval(preapproval_params)

    # Make API call & get response
    @preapproval_response = PAYPAL_API.preapproval(@preapproval)
    logger.info "\r\n@preapproval_response = #{@preapproval_response.inspect}"

    # Access Response
    if @preapproval_response.success?
      @preapproval_response.preapprovalKey
    else
      logger.info "\r\n@preapproval_response.error = #{@preapproval_response.error.map(&:message)}"
    end

    "https://www.sandbox.paypal.com/webscr?cmd=_ap-preapproval&preapprovalkey=#{@preapproval_response.preapprovalKey}"
  end

  def preapproval_params
    host = Rails.env.production? ? 'impulsideas.com' : '0.0.0.0:3000'
    {
      :cancelUrl => new_project_contribution_url(self.project, host: host),
      :returnUrl => project_url(self.project, host: host),
      :startingDate => Time.now,
      :endingDate => 180.days.from_now.localtime,
      :currencyCode => "USD",
      :memo => "Aporte al proyecto #{self.project.title}",
      :ipnNotificationUrl => ipn_notifications_url(self.id, host: host),
      :maxAmountPerPayment => self.amount,
      :maxTotalAmountOfAllPayments => self.amount,
      :maxNumberOfPayments => 1,
      :maxNumberOfPaymentsPerPeriod => 1,
      :pinType => "NOT_REQUIRED",
      :feesPayer => "PRIMARYRECEIVER",
      :displayMaxTotalAmount => false
    }
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]
  before_action :check_country, only: [:new, :create]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = @project.contributions.all
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
  end

  # GET /contributions/new
  def new
    @contribution = @project.contributions.build
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = @project.contributions.build(contribution_params)
    @contribution.user = current_user

    # respond_to do |format|
      if @contribution.save
        redirect_to @contribution.paypal_url
        # format.html { redirect_to [@project, @contribution], notice: 'Contribution was successfully created.' }
        # format.html { redirect_to @project, notice: 'La contribución se realizó satisfactoriamente.' }
        # format.json { render action: 'show', status: :created, location: [@project, @contribution] }
      else
        flash[:error] = @contribution.errors.full_messages
        render action: 'new'
        # format.html { render action: 'new' }
        # format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to [@project, @contribution], notice: 'Contribution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to project_contributions_url }
      format.json { head :no_content }
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = @project.contributions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:amount)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= simple_form_for [@project, @contribution] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amount, label: 'Cantidad', placeholder: 'RD$ 1,000' %>
  </div>

  <br>

  <div class="form-actions">
    <%= f.button :submit, 'Pagar con Paypal', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @contribution] %> |
<%= link_to 'Back', project_contributions_path %>

app/views/contributions/index.html.erb
<h1>Lista contribuciones para <%= @project.title %></h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Aporte</th>
      <th>Usuario</th>
      <th>Fecha</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= link_to contribution.id, project_contribution_path(@project, contribution) %></td>
        <td><%= number_to_currency(contribution.amount) %></td>
        <td><%= contribution.user.email %></td>
        <td><%= contribution.updated_at.strftime('%b/%d - %l:%M %p') %></td>
        <td><%#= link_to 'Show', [@project, contribution] %></td>
        <td><%#= link_to 'Edit', edit_project_contribution_path(@project, contribution) %></td>
        <td><%#= link_to 'Destroy', [@project, contribution] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_project_contribution_path(@project) %>

app/views/contributions/new.html.erb
<h1>Contribuir para <%= @project.title %></h1>

<%= render 'form' %>

app/views/contributions/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= @contribution.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @contribution.payment_status %>
</p>

<%= link_to 'Edit', edit_project_contribution_path(@project, @contribution) %> |
<%= link_to 'Back', project_contributions_path(@project) %>