config/routes.rb
Impulsideas::Application.routes.draw do
  post 'ipn_notifications/:contribution_id',
    to: 'payment_notifications#create',
    as: 'ipn_notifications'

  get 'contact_form/new'
  get 'contact_form/create'
  get 'about/faq'
  get 'about/faq_en'
  get 'about/index'
  get 'about/main'
  get 'about/terms'
  get 'about/terms_en'
  get 'about/landing'
  get 'about', to: 'about#index', as: 'about'

  resources :contact_form, only: :create
  resources :payment_notifications

  mount RedactorRails::Engine => '/redactor_rails'

  resources :projects do
    resources :items, shallow: true
    get 'orders', on: :member
  end

  resources :orders, except: [:update, :destroy, :new, :edit] do
    get 'execute', on: :member
    get 'event/:event' => 'orders#event', on: :member, as: 'event'
  end

  get 'items', to: 'items#index', as: 'items'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }

  root 'about#main'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def terms
  end

  def terms_en
  end

  def faq
  end

  def faq_en
  end

  def landing
    render layout: false
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/faq.html.erb
<%
faq = {
  general: [
   {q: '¿Qué es Impulsideas?', a: 'Impulsideas es una plataforma de Comercio Colaborativo en donde los clientes, vendedores y desarrolladores pueden hacer realidad sus ideas, proyectos, deseos y/o expectativas de negocios.'},
    {q: '¿Qué es Comercio Colaborativo?', a: 'Comercio Colaborativo es el acto de compra y venta de productos en base a un propósito en común.'},
    {q: '¿Cuál es el propósito en común en Impulsideas?', a: 'Colaborar con el desarrollo de nuevos productos (artículos, servicios o eventos).'},
    {q: '¿Cuál es el beneficio del Comercio Colaborativo?', a: 'La sociedad obtiene un modelo de negocios ganar-ganar-ganar como sigue:
<br>- Los clientes obtienen mejores productos.
<br>- Los vendedores obtienen más clientes, ventas y exposición en el mercado (a bajos costos).
<br>- Los desarrolladores obtienen fondos, promoción y clientes sin caer en riesgos financieros.'},
    {q: '¿Quién puede usar Impulsideas?', a: 'Gente de casi todo el mundo puede contribuir en Impulsideas. Apoyadores desde la India, Singapur, Taiwan y Malasia no son aceptados.'},
    {q: '¿Qué es una campaña?', a: 'Llamamos campaña al proyecto registrado de un emprendedor. Es decir, una campaña es un proyecto en proceso de recaudación de fondos.'},
    {q: '¿Por qué las personas apoyan las campañas?', a: 'Por lo general, porque quieren consumir, usar o participar del producto que la idea ofrece.'},
    {q: '¿Qué cuesta utilizar Impulsideas?', a: '1- Es de registro gratuito. <br> 2- Impulsideas cobra un 5% de los productos vendidos en su marketplace más los cargos por costos transaccionales, si el proyecto asociado a los productos alcanza su meta de recaudación dentro de la fecha límite. Si el proyecto no alcanza su meta, entonces Impulsideas cobra un 9% de los productos vendidos más los cargos por la transacción de los fondos.'},
    {q: '¿Cómo cancelo mi cuenta?', a: 'Cuentas que tengan campañas en proceso, necesitan mantenerse activas. Para cancelarla dirígete a “Editar Cuenta” y haz click en boton borrar'}
    ],
  emprendedores: [
    {q: '¿Qué necesito hacer para recaudar fondos en Impulsideas?', a: '1. Una idea para desarrollar un producto o evento.<br/>2. Un video de máximo 5 minutos que explique tu idea.<br>3. Una meta monetaria para recaudar en un rango de tiempo de máximo 60 días.<br>4. Muchas ganas de lograr tu meta.<br>'},
    {q: '¿Qué gano si alcanzo las metas de mi campaña en Impulsideas?', a: 'Ganas los fondos que necesitas para desarrollar tu producto o evento.'},
    {q: '¿Quién puede participar como emprendedor?', a: 'Toda persona física (particular) no jurídica (empresa):<br>- Residente en República Dominicana.<br>- Portador de cédula de identidad.'},
    {q: '¿Qué tipo de proyectos puedo someter?', a: 'Impulsideas se enfoca en los siguientes proyectos:<br><b>a. Comerciales.</b> Actividad que cree oferta y demanda en el mercado dentro de las siguientes categorías: Arte, Software, Moda, Juegos, Publicidad, Comida y Diseño.<br><b>b. Causa Social.</b> Actividad de recaudación de fondos para desarrollar situaciones de interés común para la sociedad - no se permiten proyectos relacionados a eventos catastróficos.<br>'},
    {q: '¿Qué tipo de proyectos NO puedo someter?', a: '- No se permiten proyectos personales: evento o asunto de beneficio personal (boda, cumpleaños, etc.). No cumple con crear oferta y demanda en el mercado.<br>- No se permiten proyectos empresariales: proyecto con el propósito de mantener una empresa.'},
    {q: '¿Cuántos proyectos puedo impulsar al año?', a: 'Se permiten cuatro (4) proyectos por emprendedor al año.'},
    {q: '¿Cuántas campañas puedo tener activas al mismo tiempo?', a: 'Se permiten dos (2) campañas simultáneas por cuenta.'},
    {q: '¿Cómo recibo los fondos recaudados?', a: 'Impulsideas utiliza a Paypal como plataforma para tramitar pagos. Cuando te inscribes como “Emprendedor” puedes vincular tu cuenta de Paypal a tu cuenta de Impulsideas. Si no tienes una cuenta de Paypal puedes pagar con tu tarjeta desde paypal tambien. Adicionalmente, si tienes preguntas sobre como retirar tus fondos desde República Dominicana envianos un correo a <a href="mailto:servicio@impulsideas.com">servicio@impulsideas.com</a>.'},
    {q: '¿Qué pasa si alguien más hace un proyecto parecido a mi idea?', a: 'En Impulsideas no somos responsables de que alguien someta una idea parecida antes o después de usted haber publicado su proyecto. Lo ideal es que, si su idea puede ser replicada, tome todas las medidas legales para salvaguardar su proyecto antes de publicarlo, y que no comunique la información que considere como secreta y/o esencial en su página de proyectos.'},
    {q: '¿Cuánto tiempo tengo para recaudar fondos? ', a: 'Tienes máximo 60 días para alcanzar tus metas en una campaña. '},
    ],
  contribuidores: [
    {q: '¿Cómo puedo contribuir a proyectos en Impulsideas?', a: '- Como vendor puedes vender productos para apoyar los proyectos que te interesan<br>- Como cliente puedes comprar y/o promover productos para apoyar los proyectos que te interesan'},
    {q: '¿Quién puede participar como contribuidor?', a: '- Como cliente, cualquier persona en el mundo que sea portador de una tarjeta de crédito, débito o una cuenta de Paypal. <br>- Como vendedor, cualquier persona que tenga los derechos para vender un producto. <br>- Contribuidores desde la India, Singapur, Taiwán y Malasia no son aceptados todavía.'},
    {q: '¿Existe un límite superior para precio de los productos vendidos en Impulsideas?', a: 'Existe un tope máximo de US$400.00 (o su equivalente en la moneda de tu país) por transacción. Cada cliente puede hacer un máximo de 4 compras por proyecto.'},
    {q: '¿Qué gano con contribuir a proyectos?', a: '- Contribuir a que el proyecto se haga realidad.<br>- Obtienes los productos que compraste para contribuir'},
    {q: '¿A quién debo contactar si tengo una pregunta sobre mi contribución? ', a: 'Si usted tiene una pregunta acerca de una compra o necesita más información sobre algun pago, póngase en contacto con el dueño del producto. Si necesita mas ayuda envíenos un email a <a href="mailto:servicio@impulsideas.com">servicio@impulsideas.com</a>.'},
    {q: '¿Cómo sé que los fondos recaudados van a ser utilizados en el proyecto presentado?', a: "Los emprendedores se hacen responsables de desarrollar su proyecto como lo establecen los #{link_to "Terminos de uso", about_terms_path}."}
  ]
}
%>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-9">
    <div class="page-header">
      <h1>FAQs</h1>
    </div>
    <p><%= link_to "English", about_faq_en_path %></p>
    <% faq.each do |header, questions| %>
      <h3><%= header.to_s.titleize %></h3>
      <ul class="faq">
        <% questions.each do |question| %>
        <li>
          <a href="#" class="question"><%= question[:q] %></a>
          <p class="answer well"><%=raw question[:a] %></p>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/about/faq_en.html.erb
<%
faq = {
  general: [
   {q: 'What is Impulsideas?', a: 'Impulsideas is a Collaborative Commerce platform where customers and vendors trade products in its marketplace, so developers can bring to life their ideas, projects, wishes or/and business expectations.'},
    {q: 'What is Collaborative Commerce?', a: 'Collaborative Commerce (C-Commerce) is defined as the trade of products for a shared purpose.'},
    {q: 'What is the shared purpose of Impulsideas?', a: 'Collaborate with the creation of new products (goods, services and/or events).'},
    {q: 'What is the benefit of Collaborative Commerce?', a: 'Society gets a win-win-win business model as follows:
<br>- Customers get better products.
<br>- Vendors get more customers, sales, and exposure at low cost.
<br>- Developers get funds, promotion and customer relationship without financial risks.'},
    {q: 'Who can use Impulsideas?', a: 'People of almost everywhere can participate in Impulsideas - Supporters (vendors and/or customers) from India, Singapore, Taiwan and Malaysia are not accepted due to their particular information regulations.'},
    {q: 'What is a Campaign?', a: 'A campaign is an ongoing project promoting certain Items and Sponsored Items.'},
    {q: 'Why people support project?', a: 'Usually because they want the product offered or want to participate of the idea that the project offers.'},
    {q: 'What are the fees involved?', a: '1. Impulsideas is of free registration.<br>
2. Impulsideas charges 5% of the items sold plus the applicable transactional fees for projects that reach their goals. Otherwise, Impulsideas charge 9% of the items sold plus the applicable transactional fees.'},
    {q: 'How do I cancel my account?', a: 'You can cancel your account as long as there are no projects in process. Accounts with projects in progress, can not be cancelled.<br>To cancel go to " Edit Account " and click “Cancel Account”.'}
    ],
  entrepreneurs: [
    {q: 'What do I need to raise funds with Impulsideas?', a: '1. An idea to develop a product and/or  service or event.
<br>2. A video of maximum 5 minutes explaining your idea.
<br>3. A monetary goal to raise in a time frame of up to 60 days.
<br>4.  A product to sell.
<br>5. Eagerness to achieve your goal.'},
    {q: 'What do I get if I reach my Impulsideas campaign goals?', a: '1. Get the funds you need to develop your product or event.
<br>2. Get the contacts of all those who supported your project - there may be anonymous contributors whose contact information cannot be shared.
<br>3. Get exposure to possible clients and supporters during the campaign and when it ends you get permanent exposure on the successful projects page.'},
    {q: 'What do I get if I don’t reach my Impulsideas campaign goals?', a: '1. Get the funds you raised for your product or event.
<br>2. Get the contacts of all those who supported your project - there may be anonymous contributors whose contact information cannot be shared.
<br>3. Get exposure to possible clients and supporters during the campaign and when it ends you get permanent exposure on the successful projects page.
'},
    {q: 'Who can participate as an entrepreneur?', a: 'Any person (No companies):
<br>- Resident of Dominican Republic.
<br>- At least 18 years old.
<br>- With an accepted ID.'},
    {q: 'What type of projects can I submit??', a: 'Impulsideas focuses on the following projects:

<br>Commercial. Activity that creates supply and demand in the market within the following categories: Arts, Software, Fashion, Games, Advertising, Food, Design, Tools, Electronics and Services.


<br>Note:
<br>Personal projects are not allowed: Event or matter of personal benefit (wedding, birthday, etc.). It does not meet the create supply and demand in the market condition.

<br>Business projects are not allowed: Project in order to maintain an established business.'},
    {q: 'How many projects can I promote a year?', a: 'Four (4) projects a year per entrepreneur are allowed.'},
    {q: 'How many campaigns can be active at the same time?', a: 'Two (2) simultaneous campaigns per account are permitted.'},
    {q: 'How do I receive the raised funds?', a: 'Impulsideas uses Paypal as a payment process platform. When you sign up as an "Entrepreneur" You can link your Paypal account to your Impulsideas account. If you do not have a Paypal account, you can create one by going to "this link". Additionally, if you need support for withdrawing your funds from Dominican Republic send us an email to <a href="mailto:servicio@impulsideas.com">servicio@impulsideas.com</a>.'},
    {q: 'What if someone else makes a similar project to my idea?', a: 'In Impulsideas we are not responsible if anyone submits a similar idea before or after you have published your project idea. Ideally, if your idea can be replicated, take all legal measures to safeguard your project before publishing it, and do not communicate information deemed secret and / or essential on your project page.'},
    {q: 'How long do I have to promote my campaign?', a: 'You have up to 60 days to reach your campaign goal.'},
    ],
  supporters: [
    {q: 'Who can participate as a supporter?', a: 'As a customer: Anyone in the world who owns a credit card, debit card or a Paypal account. <br>As a vendor: Anyone with the rights to sell a product. Supporters from India, Singapore, Taiwan and Malaysia are not accepted.'},
    {q: 'How I can support projects?', a: 'As a customer by buying Items and/or sponsored Items you consider. As a vendor by providing a product which sales could be shared with the project developer.'},
    {q: 'Is there an upper limit for the value of the products sold?', a: 'There is a maximum of U.S. $ 400.00 (or its equivalent in the currency of your country) per transaction. Each client can make a maximum of 4 purchaces per project.'},
    {q: 'What do I get by supporting projects?', a: '- You help make a project a reality.
<br>- Get products according to items bought – and as determined by project owners.'},
    {q: 'Who do I contact if I have questions about my purchase?', a: 'If you have a question about an item or need more information about a purchase, contact the product vendor. For any other questions, email us at <a href="mailto:servicio@impulsideas.com">servicio@impulsideas.com</a>.'},
    {q: 'How do I know that the funds raised will be used in the project presented?', a: "Entrepreneurs are responsible for developing the project. Vendors are responsibles of sending the items to supporters as set out in their campaign through the Terms of Use.
"},
  {q: 'Do we have any internal Processes for Anti-Money Laundering Project monitoring or Vetting?', a: "Our Processes for AML include but are not limited to:
<br>1. An Anti-Money Laundering program:
<br>1.1. Including automatic and periodic background checks.
<br>2 . A customer identification program for Both creators and Donors:
<br>2.1. Including but not limited to ID, passports and credit cards.
<br>3 . Reporting any suspicious activity to the competent Authorities.
<br>4 . Complying with requests for information from the financial crimes enforcement networks.
"}

  ]
}
%>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-9">
    <div class="page-header">
      <h1>FAQs</h1>
    </div>
    <p><%= link_to "Español", about_faq_path %></p>
    <% faq.each do |header, questions| %>
      <h3><%= header.to_s.titleize %></h3>
      <ul class="faq">
        <% questions.each do |question| %>
        <li>
          <a href="#" class="question"><%= question[:q] %></a>
          <p class="answer well"><%=raw question[:a] %></p>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/about/index.html.erb
<h1>Preguntale a Pericles</h1>
<p>Mas informacion acerca de como aportar, crear proyectos y demas</p>

app/views/about/landing.html.erb
<%= image_tag 'Impulsideas.png', height: '400px' %>

app/views/about/main.html.erb
<% content_for :header do %>
  <header class="hhero">
    <h1>Comercio Colaborativo</h1>
    <hr class="star-light">
    <h2>Desarrolla Proyectos · Vende Productos</h2>
  </header>

  <article id="works" class="three-columns">
    <h1>Como Funciona</h1>
    <hr class="star-primary">

    <section>
      <div class="box onethree">
        <span class="fa-stack fa-5x icons">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-cogs fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Crea</h2>
        <p class="lead">Crea una campaña para tu idea e inserta tus productos en nuestra plataforma</p>
        <p><a class="btn btn-primary" href="<%= projects_path %>" role="button"> Inspírate &raquo;</a></p>
      </div>
    </section>

    <section>
      <div class="box twothree">
        <span class="fa-stack fa-5x icons">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-bullhorn fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Comparte</h2>
        <p class="lead">Promueve tus proyectos y productos. Gana exposición comunicando tu valor.</p>
        <p><a class="btn btn-primary" href="<%= new_project_path %>" role="button"> Comienza &raquo;</a></p>
      </div>
    </section>

    <section>
      <div class="box threethree">
        <span class="fa-stack fa-5x icons">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-money fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Recibe</h2>
        <p class="lead">Recibe los ingresos logrados y comienza a hacer tus proyectos realidad.</p>
        <p><a class="btn btn-primary" href="<%= new_project_path %>" role="button"> Gana &raquo;</a></p>
      </div>
    </section>
  </article>

  <article id="about" class="two-columns-responsive">
    <h1>Nosotros</h1>
    <hr class="star-light">
    <section>
      <p>Somos una empresa dominicana que busca impulsar el emprendedurismo en nuestro país. Conectamos emprendedores con contribuyentes en cualquier parte del mundo. ¡Te conéctamos con personas interesadas en apoyarte a lograr tus sueños!</p>
    </section>
  </article>

  <article class="featured">
    <h1 class="title"><%= link_to 'Proyectos destacados', projects_path %></h1>
    <hr class="star-primary">
    <section>
      <% projects = Project.order("id desc").limit(3) %>
      <% if projects.any? %>
        <div id="projects_container">
          <% projects.each do |project| %>
            <div class="col-sm-6 col-md-4 project_item">
              <%= render 'projects/project_thumbnail', project: project %>
            </div>
          <% end %>
        </div>
      <% else %>
        <h2>No hay projectos para mostrar. Crear uno nuevo <%= link_to "aqui.", new_project_path %></h2>
      <% end %>
    </section>
  </article>
<% end %>