config/routes.rb
Impulsideas::Application.routes.draw do
  post 'ipn_notifications/:contribution_id',
    to: 'payment_notifications#create',
    as: 'ipn_notifications'

  get 'contact_form/new'
  get 'contact_form/create'
  get 'about/faq'
  get 'about/faq_en'
  get 'about/index'
  get 'about/main'
  get 'about/terms'
  get 'about/terms_en'
  get 'about/landing'
  get 'about', to: 'about#index', as: 'about'

  resources :contact_form, only: :create
  resources :payment_notifications

  mount RedactorRails::Engine => '/redactor_rails'

  resources :projects do
    resources :items, shallow: true
    get 'orders', on: :member
  end

  resources :orders, except: [:update, :destroy, :new, :edit] do
    get 'execute', on: :member
    get 'event/:event' => 'orders#event', on: :member, as: 'event'
  end

  get 'items', to: 'items#index', as: 'items'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }

  root 'about#main'
end

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide hidden-xs" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="item active">
      <%= image_tag 'goal.jpg', alt: 'First Slide', class: 'img-responsive' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Sueña</h1>
          <p>Tu tienes metas que mercen ser alcanzadas,<br>Tu tienes sueños que merecen hacerse realidad.</p>
          <%= link_to 'Empieza', projects_path, class: 'btn btn-lg btn-primary' %>
        </div>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'blueprint.jpg', alt: 'Second Slide', class: 'img-responsive' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Soporta ideas!</h1>
          <p>Gran número de proyectos emprendidos fracasan debido a la falta de recursos. Puedes cambiar eso hoy.</p>
          <%= link_to 'Apoya', projects_path, class: 'btn btn-lg btn-primary' %>
          <p></p>
        </div>
      </div>
    </div>

    <div class="item">
      <%= image_tag 'support2.jpg', alt: 'Third Slide', class: 'img-responsive' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Consigue Apoyo</h1>
          <p>Publica tu proyecto con nosotros y estas a otro paso de hacerlo realidad.</p>
          <%= link_to 'Crea', new_project_path, class: 'btn btn-lg btn-primary' %>
          <p></p>
        </div>
      </div>
    </div>

  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-menu-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path do %>
        <div class="logo">
          <%#= image_tag 'logo.png' %>
          <%= image_tag 'Impulsideas4.png' %>
        </div>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-menu-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li class="page-scroll">
          <a href="/#works"><i class="fa fa-cogs big-icon"></i> Funcionamiento</a>
        </li>
        <li class="page-scroll">
          <a href="/#about"><i class="fa fa-lightbulb-o"></i> Nosotros</a>
        </li>
        <li class="page-scroll <%= current_page?(items_path) ? 'active' : '' %>"><%= link_to items_path do %>
            <span class="fa fa-globe"></span> Marketplace
          <% end %>
        </li>
        <li class="page-scroll <%= current_page?(projects_path) ? 'active' : '' %>"><%= link_to projects_path do %>
            <span class="fa fa-search"></span> Explora
          <% end %>
        </li>
        <li class="page-scroll <%= current_page?(new_project_path) ? 'active' : '' %>">
          <%= link_to new_project_path do %>
            <span class="fa fa-cog"></span> Crea
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-no-turbolink="true"><span class="fa fa-user"></span> <%= current_user.emailname %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to edit_user_registration_path do %>
                <span class="fa fa-edit"></span> Editar cuenta
              <% end %>
              <li><%= link_to orders_path do %>
                <span class="fa fa-money"></span> Ordenes
              <% end %>
              </li>
              <li class="divider"></li>
              <li><%= link_to destroy_user_session_path, :method=>'delete' do %>
                <span class="fa fa-sign-out"></span> Salir
              <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="fa fa-user"></span> Entrar
            <% end %>
          </li>
        <% end %><!-- if user_signed_in? -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "Impulsideas" %></title>

    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "collaborative ecommerce webiste" %>">

    <%= favicon_link_tag 'plane-white.ico' %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <%= javascript_include_tag :modernizr %>
    <!-- Replaced by modernizr // <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> -->

    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div id="wrapper">
      <%= yield(:header) if content_for? :header %>

      <div id="main-content">
        <%= render 'shared/flash_messages', flash: flash %>
        <%= yield %>
      </div>

      <aside></aside>
    </div><!-- div#wrapper -->

      <footer>
        <p>Copyright © <%= Time.now.year %>  <strong>GAPEK, SRL</strong> · Developed by <strong><a href="http://adrianmejia.com">Adrian Mejia</a></strong></p>
        <div>
          <a href="https://www.facebook.com/impulsideas">
            <span class="fa-stack fa-2x">
              <i class="fa fa-circle-thin fa-stack-2x"></i>
              <i class="fa fa-facebook fa-stack-1x"></i>
            </span>
          </a>

          <a href="mailto:email@impulsideas.com">
            <span class="fa-stack fa-2x">
              <i class="fa fa-circle-thin fa-stack-2x"></i>
              <i class="fa fa-envelope fa-stack-1x"></i>
            </span>
          </a>
        </div>
      </footer>

    <!-- SCRIPTS -->
    <%= javascript_include_tag "application" %>
    <%= analytics_init if Rails.env.production? %>
    <!-- FIXME: add it to the assets pipeline -->
    <script>
      $.getScript('//cdn.jsdelivr.net/isotope/1.5.25/jquery.isotope.min.js',function(){
        $('#projects_container').isotope({
          itemSelector : '.project_item',
          layoutMode : 'fitRows'
        });
      });
    </script>
  </body>
</html>